# Generated by Django 5.2.4 on 2025-09-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default='Weight-15000 gClass -Fish feedPellet Size - 4.5mm'),
            preserve_default=False,
        ),
    ]
