# Generated by Django 5.2.4 on 2025-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_choice',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ECOPIA_STAFF', 'Ecopia_Staff'), ('CUSTOMER', 'Customer'), ('WASTE_PROVIDER', 'WASTE_PROVIDER')], default='CUSTOMER', max_length=20),
        ),
    ]
